// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
@ffi.DefaultAsset('package:flutter_soloud/src/bindings.cpp')
library;

import 'dart:ffi' as ffi;

/// ///////////////////////////////////////////////////////////
/// Dart callbacks, engine lifecycle and mixer output capture
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void nativeFree(ffi.Pointer<ffi.Void> pointer);

/// The callback to monitor when a voice ends.
///
/// It is called by void `Soloud::stopVoice_internal(unsigned int aVoice)`
/// when a voice ends and comes from the audio thread (so on the web, from a
/// different web worker).
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.UnsignedInt>)>()
external void voiceEndedCallback(ffi.Pointer<ffi.UnsignedInt> handle);

/// Requests a device-idle evaluation after SoLoud stops or pauses a voice.
/// SoLoud invokes this only after releasing its audio mutex.
@ffi.Native<ffi.Void Function()>()
external void voiceInactiveCallback();

/// Set a Dart functions to call when an event occurs.
///
/// [owner_engine_id] is the FlutterEngine whose isolate created these
/// trampolines, or -1 where no engine lifecycle is available. It is recorded
/// so that a detaching or hot-restarting engine can retire *its own*
/// callables and never somebody else's.
@ffi.Native<
  ffi.Void Function(
    dartVoiceEndedCallback_t,
    dartFileLoadedCallback_t,
    dartStateChangedCallback_t,
    ffi.Int64,
  )
>()
external void setDartEventCallback(
  dartVoiceEndedCallback_t voice_ended_callback,
  dartFileLoadedCallback_t file_loaded_callback,
  dartStateChangedCallback_t state_changed_callback,
  int owner_engine_id,
);

@ffi.Native<ffi.Void Function()>()
external void clearDartCallbackRegistrations();

/// Retire every Dart callable owned by [engine_id] because its isolate is
/// going away (a hot restart, or its FlutterEngine being destroyed). Returns
/// false when a different engine owns the live registration, so a detaching
/// engine never retires another one's callables.
@ffi.Native<ffi.Bool Function(ffi.Int64)>()
external bool clearDartCallbackRegistrationsForEngine(int engine_id);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void retireDartCallbacksFinalizer(ffi.Pointer<ffi.Void> token);

/// Start capturing the master mixer output.
///
/// [format] the output format from the MixerOutputFormat enum.
/// [sampleRate] desired sample rate, or <=0 to use the engine sample rate.
/// [channels] desired channel count, or <=0 to use the engine channel count.
/// [bufferSizeBytes] size of the circular buffer in bytes.
/// [notificationThresholdBytes] number of available bytes before a callback
/// is fired.
/// [chunkPCMFrames] fixed PCM chunk size in frames, or 0 to disable chunk
/// mode.
/// Returns [PlayerErrors.noError] if success.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Int, ffi.Int, ffi.Int, ffi.Int, ffi.Int, ffi.Int)
>(symbol: 'startMixerCapture')
external int _startMixerCapture(
  int format,
  int sampleRate,
  int channels,
  int bufferSizeBytes,
  int notificationThresholdBytes,
  int chunkPCMFrames,
);

PlayerErrors startMixerCapture(
  int format,
  int sampleRate,
  int channels,
  int bufferSizeBytes,
  int notificationThresholdBytes,
  int chunkPCMFrames,
) => PlayerErrors.fromValue(
  _startMixerCapture(
    format,
    sampleRate,
    channels,
    bufferSizeBytes,
    notificationThresholdBytes,
    chunkPCMFrames,
  ),
);

/// Stop capturing the master mixer output.
@ffi.Native<ffi.Void Function()>()
external void stopMixerCapture();

/// Returns 1 if mixer capture is running, 0 otherwise.
@ffi.Native<ffi.Int Function()>()
external int isMixerCaptureRunning();

/// Get the pointer to the circular capture buffer.
@ffi.Native<ffi.Pointer<ffi.UnsignedChar> Function()>()
external ffi.Pointer<ffi.UnsignedChar> getMixerCaptureBufferPointer();

/// Get the total size of the circular capture buffer in bytes.
@ffi.Native<ffi.Int Function()>()
external int getMixerCaptureBufferSize();

/// Get the number of bytes available to read in the capture buffer.
@ffi.Native<ffi.Int Function()>()
external int getMixerCaptureAvailableBytes();

/// Get the current read offset in the capture buffer.
@ffi.Native<ffi.Int Function()>()
external int getMixerCaptureReadOffset();

/// Advance the read position by [bytes].
@ffi.Native<ffi.Void Function(ffi.Int)>()
external void advanceMixerCaptureReadPosition(int bytes);

/// Get a malloc'd copy of the WAV header of the current capture, or nullptr
/// when the capture format has none. Free with nativeFree().
@ffi.Native<ffi.Pointer<ffi.UnsignedChar> Function()>()
external ffi.Pointer<ffi.UnsignedChar> getMixerOutputWavHeader();

/// Publish the mixer-output data callable for [owner_engine_id].
/// Returns whether the callable was published.
@ffi.Native<ffi.Bool Function(dartMixerOutputDataCallback_t, ffi.Int64)>()
external bool setMixerOutputCallbackForEngine(
  dartMixerOutputDataCallback_t callback,
  int owner_engine_id,
);

/// Lifecycle-free entry point, for hosts where no registration is ever
/// claimed. The web build binds this exported symbol directly from the
/// prebuilt wasm, so its signature must not change.
@ffi.Native<ffi.Void Function(dartMixerOutputDataCallback_t)>()
external void setMixerOutputCallback(dartMixerOutputDataCallback_t callback);

@ffi.Native<ffi.Bool Function(dartVisualizationCallback_t, ffi.Int64)>()
external bool setVisualizationCallbackForEngine(
  dartVisualizationCallback_t callback,
  int owner_engine_id,
);

@ffi.Native<ffi.Void Function(dartVisualizationCallback_t)>()
external void setVisualizationCallback(dartVisualizationCallback_t callback);

/// Check if the libopus and libogg are available at build time.
@ffi.Native<ffi.Bool Function()>()
external bool areXiphLibsAvailable();

/// Initialize the player. Must be called before any other player functions.
///
/// [sampleRate] the sample rate. Usually is 22050, 44100 (CD quality) or
/// 48000.
/// [bufferSize] the audio buffer size. Usually is 2048, but can be also 512
/// when low latency is needed for example in games. [channels] 1=mono,
/// 2=stereo, 4=quad, 6=5.1, 8=7.1.
/// [devicePeriodFrames] small output device period used when
/// [renderAheadFrames] enables the render-ahead ring; 0 = default (512).
/// [renderAheadFrames] depth of the engine-owned render-ahead ring in
/// frames; 0 disables it and keeps direct-to-device mixing.
///
/// Returns [PlayerErrors.noError] if success.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Int,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
  )
>(symbol: 'initEngine')
external int _initEngine(
  int deviceID,
  int sampleRate,
  int bufferSize,
  int channels,
  int lowLatency,
  int devicePeriodFrames,
  int renderAheadFrames,
);

PlayerErrors initEngine(
  int deviceID,
  int sampleRate,
  int bufferSize,
  int channels,
  int lowLatency,
  int devicePeriodFrames,
  int renderAheadFrames,
) => PlayerErrors.fromValue(
  _initEngine(
    deviceID,
    sampleRate,
    bufferSize,
    channels,
    lowLatency,
    devicePeriodFrames,
    renderAheadFrames,
  ),
);

/// Android only: choose whether SoLoud tags the AAudio stream's
/// usage/contentType (media/music) or leaves them unset so the app can
/// manage AudioAttributes externally (e.g. via the audio_session plugin).
/// Only takes effect with low-latency disabled. Call before initEngine().
/// No effect on other backends. [managed] != 0 → media/music (default);
/// 0 → leave unset.
@ffi.Native<ffi.Void Function(ffi.UnsignedInt)>()
external void setAndroidAAudioAttributes(int managed);

/// Set how long the audio output device keeps running while the engine is
/// idle (no active voices) before it is automatically stopped, on every
/// platform. [timeoutMs] < 0 keeps the device running indefinitely while
/// idle (the deferred idle-pause is suppressed, so the device keeps
/// rendering silence and the app keeps its OS audio session alive) and
/// starts it immediately if it was stopped. [timeoutMs] == 0 stops the
/// device as soon as possible once idle. [timeoutMs] > 0 keeps it running
/// for that many milliseconds after going idle. Any play/unpause before the
/// deadline cancels the pending stop. The default is 500. Can be called any
/// time.
@ffi.Native<ffi.Void Function(ffi.Int64)>()
external void setAudioDeviceIdleTimeout(int timeoutMs);

/// Stop the audio output device without deinitializing the engine. By
/// default this is a successful no-op while voices are active. [force]
/// stops the device even during active playback without mutating any voice.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt)>(
  symbol: 'stopAudioDevice',
)
external int _stopAudioDevice(int force);

PlayerErrors stopAudioDevice(int force) =>
    PlayerErrors.fromValue(_stopAudioDevice(force));

/// Restart the audio output device previously stopped by stopAudioDevice(),
/// so existing voices and loaded sounds keep operating. Idempotent: a no-op
/// if the device is already started.
@ffi.Native<ffi.UnsignedInt Function()>(symbol: 'startAudioDevice')
external int _startAudioDevice();

PlayerErrors startAudioDevice() => PlayerErrors.fromValue(_startAudioDevice());

/// Get the current state of the audio output device. Returns
/// [AudioDeviceState.audioDeviceUninitialized] if the engine is not
/// initialized.
@ffi.Native<ffi.UnsignedInt Function()>(symbol: 'getAudioDeviceState')
external int _getAudioDeviceState();

AudioDeviceState getAudioDeviceState() =>
    AudioDeviceState.fromValue(_getAudioDeviceState());

/// Test-only hook that sends an interruption through miniaudio's normal
/// notification callback. This is intentionally absent from the public API.
@ffi.Native<ffi.Void Function(ffi.UnsignedInt)>()
external void debugTriggerAudioInterruption(int began);

/// List playback devices.
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Pointer<ffi.Int>>,
    ffi.Pointer<ffi.Pointer<ffi.Int>>,
    ffi.Pointer<ffi.Int>,
  )
>()
external void listPlaybackDevices(
  ffi.Pointer<ffi.Pointer<ffi.Char>> devicesName,
  ffi.Pointer<ffi.Pointer<ffi.Int>> deviceId,
  ffi.Pointer<ffi.Pointer<ffi.Int>> isDefault,
  ffi.Pointer<ffi.Int> n_devices,
);

/// Change the playback device.
///
/// [deviceID] the device ID. -1 for default OS output device.
@ffi.Native<ffi.UnsignedInt Function(ffi.Int)>(symbol: 'changeDevice')
external int _changeDevice(int deviceID);

PlayerErrors changeDevice(int deviceID) =>
    PlayerErrors.fromValue(_changeDevice(deviceID));

/// Free the list of playback devices.
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Pointer<ffi.Int>>,
    ffi.Pointer<ffi.Pointer<ffi.Int>>,
    ffi.Int,
  )
>()
external void freeListPlaybackDevices(
  ffi.Pointer<ffi.Pointer<ffi.Char>> devicesName,
  ffi.Pointer<ffi.Pointer<ffi.Int>> deviceId,
  ffi.Pointer<ffi.Pointer<ffi.Int>> isDefault,
  int n_devices,
);

/// Must be called when there is no more need of the player or when closing
/// the app.
@ffi.Native<ffi.Void Function()>()
external void dispose();

/// Claim the native engine for a FlutterEngine ahead of initializing it.
///
/// [owner_engine_id] is the FlutterEngine that will own the engine this
/// initialization creates, or -1 on platforms with no engine-lifecycle
/// hooks.
@ffi.Native<ffi.Void Function(ffi.Int64)>()
external void prepareEngineInit(int owner_engine_id);

@ffi.Native<ffi.Void Function()>()
external void requestEngineShutdown();

/// The epoch a prepare request must quote to be accepted.
@ffi.Native<ffi.Uint64 Function()>()
external int currentEngineShutdownEpoch();

/// prepareEngineInit() for a claim that was decided earlier than it is
/// taken.
///
/// Returns false, changing nothing, when a shutdown has been requested
/// since [shutdown_epoch] was read.
@ffi.Native<ffi.Bool Function(ffi.Int64, ffi.Uint64)>()
external bool prepareEngineInitForRequest(
  int owner_engine_id,
  int shutdown_epoch,
);

/// Tear the engine down because its owning FlutterEngine is being destroyed
/// while the process keeps running (the audio_service / add-to-app case).
///
/// Returns false unless [engine_id] still owns the native engine.
@ffi.Native<ffi.Bool Function(ffi.Int64)>()
external bool requestEngineTeardownForEngine(int engine_id);

@ffi.Native<ffi.Int Function()>()
external int isInited();

/// Load a new sound to be played once or multiple times later.
///
/// After loading the file, the [fileLoadedCallback] will call the
/// Dart function defined with [setDartEventCallback] which gives back
/// the error and the new hash.
///
/// [completeFileName] the complete file path.
/// [loadIntoMem] if true Soloud::wav will be used which loads
/// all audio data into memory. This will be useful when
/// the audio is short, ie for game sounds, mainly used to prevent
/// gaps or lags when starting a sound (less CPU, more memory allocated).
/// If false, Soloud::wavStream will be used and the audio data is loaded
/// from the given file when needed (more CPU, less memory allocated).
/// See the [seek] note problem when using [loadIntoMem] = false
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Bool, ffi.Uint64)>()
external void loadFile(
  ffi.Pointer<ffi.Char> completeFileName,
  bool loadIntoMem,
  int counter,
);

/// Load a new sound stored into [buffer] to be played once or multiple times
/// later. Mainly used on web because the browsers are not allowed to read
/// files directly.
///
/// [uniqueName] the unique name of the sound. Used only to have the [hash].
/// [buffer] the audio data. These contains the audio file bytes.
/// [length] the length of [buffer].
/// [loadIntoMem] if true Soloud::wav will be used which loads
/// all audio data into memory. This will be useful when
/// the audio is short, ie for game sounds, mainly used to prevent
/// gaps or lags when starting a sound (less CPU, more memory allocated).
/// If false, Soloud::wavStream will be used and the audio data is loaded
/// from the given file when needed (more CPU, less memory allocated).
/// See the [seek] note problem when using [loadIntoMem] = false
/// [hash] return the hash of the sound.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.UnsignedChar>,
    ffi.Int,
    ffi.Int,
    ffi.Pointer<ffi.UnsignedInt>,
  )
>(symbol: 'loadMem')
external int _loadMem(
  ffi.Pointer<ffi.Char> uniqueName,
  ffi.Pointer<ffi.UnsignedChar> buffer,
  int length,
  int loadIntoMem,
  ffi.Pointer<ffi.UnsignedInt> hash,
);

PlayerErrors loadMem(
  ffi.Pointer<ffi.Char> uniqueName,
  ffi.Pointer<ffi.UnsignedChar> buffer,
  int length,
  int loadIntoMem,
  ffi.Pointer<ffi.UnsignedInt> hash,
) => PlayerErrors.fromValue(
  _loadMem(uniqueName, buffer, length, loadIntoMem, hash),
);

/// Load 2 audios, convert to mono if needed, and join them into a single
/// stereo AudioSource.
/// [hash] return the hash of the sound.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.UnsignedChar>,
    ffi.Pointer<ffi.UnsignedChar>,
    ffi.Int,
    ffi.Int,
    ffi.Pointer<ffi.UnsignedInt>,
  )
>(symbol: 'joinTwoSources')
external int _joinTwoSources(
  ffi.Pointer<ffi.Char> uniqueName,
  ffi.Pointer<ffi.UnsignedChar> mem1,
  ffi.Pointer<ffi.UnsignedChar> mem2,
  int length1,
  int length2,
  ffi.Pointer<ffi.UnsignedInt> hash,
);

PlayerErrors joinTwoSources(
  ffi.Pointer<ffi.Char> uniqueName,
  ffi.Pointer<ffi.UnsignedChar> mem1,
  ffi.Pointer<ffi.UnsignedChar> mem2,
  int length1,
  int length2,
  ffi.Pointer<ffi.UnsignedInt> hash,
) => PlayerErrors.fromValue(
  _joinTwoSources(uniqueName, mem1, mem2, length1, length2, hash),
);

/// Set up an audio stream.
///
/// [maxBufferSize] the max buffer size in **bytes**. When adding audio data
/// using [addAudioDataStream] and this values is reached, the stream will
/// be considered ended (likewise we called [setDataIsEnded]). This means
/// that when playing it, it will stop at that point (if loop is not set).
///
/// **Note:** this parameter doesn't allocate any memory, but it just limits
/// the amount of data that can be added.
///
/// [bufferingTimeNeeds] the buffering time needed in seconds. If a handle
/// reaches the current buffer length, it will start to buffer pausing it
/// and waiting until the buffer will have enough data to cover this time.
///
/// [sampleRate] the sample rate. Usually is 22050 or 44100 (CD quality).
/// When using [format] as `opus`, the sample rate can be 48000, 24000,
/// 16000, 12000 or 8000. Whatever the sample rate of the incoming data is,
/// it will be resampled to this value. So, if you are adding Opus data at
/// 48 KHz, and you set this to 24000, the data will be resampled to 24 KHz.
///
/// [channels] choose the number of channels. The `opus` format
/// supports only mono and stereo.
///
/// [format] choose from `f32le`, `s8`, `s16le`, `s32le` and
/// `opus`. The last one is a special format that uses the Opus codec with
/// Ogg container. It supports only 48, 24, 16, 12 and 8 KHz sample rates
/// and mono and stereo.
///
/// [onBufferingCallback] a callback that is called when starting to buffer
/// (isBuffering = true) and when the buffering is done (isBuffering =
/// false). The callback is called with the `handle` which triggered the
/// event and the `time` in seconds.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.UnsignedInt>,
    ffi.UnsignedLong,
    ffi.Int,
    ffi.Double,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.Int,
    dartOnBufferingCallback_t,
    dartOnMetadataCallback_t,
  )
>(symbol: 'setBufferStream')
external int _setBufferStream(
  ffi.Pointer<ffi.UnsignedInt> hash,
  int maxBufferSize,
  int bufferingType,
  double bufferingTimeNeeds,
  int sampleRate,
  int channels,
  int format,
  dartOnBufferingCallback_t onBufferingCallback,
  dartOnMetadataCallback_t onMetadataCallback,
);

PlayerErrors setBufferStream(
  ffi.Pointer<ffi.UnsignedInt> hash,
  int maxBufferSize,
  int bufferingType,
  double bufferingTimeNeeds,
  int sampleRate,
  int channels,
  int format,
  dartOnBufferingCallback_t onBufferingCallback,
  dartOnMetadataCallback_t onMetadataCallback,
) => PlayerErrors.fromValue(
  _setBufferStream(
    hash,
    maxBufferSize,
    bufferingType,
    bufferingTimeNeeds,
    sampleRate,
    channels,
    format,
    onBufferingCallback,
    onMetadataCallback,
  ),
);

/// Resets the buffer of the data stream.
/// [hash] the hash of the stream sound.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt)>(
  symbol: 'resetBufferStream',
)
external int _resetBufferStream(int hash);

PlayerErrors resetBufferStream(int hash) =>
    PlayerErrors.fromValue(_resetBufferStream(hash));

/// Get the time consumed by the stream of a type `BufferingType.RELEASED`
/// with hash [hash].
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.Pointer<ffi.Float>)>(
  symbol: 'getStreamTimeConsumed',
)
external int _getStreamTimeConsumed(
  int hash,
  ffi.Pointer<ffi.Float> timeConsumed,
);

PlayerErrors getStreamTimeConsumed(
  int hash,
  ffi.Pointer<ffi.Float> timeConsumed,
) => PlayerErrors.fromValue(_getStreamTimeConsumed(hash, timeConsumed));

/// Set the icy metadata integer value. Must be set once before calling
/// the first time [addAudioDataStream] to be able to get MP3 metadata
/// of a stream.
///
/// [hash] the hash of the stream sound.
/// [icyMetaInt] the icy metadata integer value. Default is 16000 which
/// is the most used value.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.Int)>(
  symbol: 'setBufferIcyMetaInt',
)
external int _setBufferIcyMetaInt(int hash, int icyMetaInt);

PlayerErrors setBufferIcyMetaInt(int hash, int icyMetaInt) =>
    PlayerErrors.fromValue(_setBufferIcyMetaInt(hash, icyMetaInt));

/// Set up a pull-based audio stream.
///
/// [audioSizeBytes] the total size in **bytes** of the original encoded or
/// PCM stream. This is used to compute the total audio duration and to
/// request the tail chunk for formats where the duration is not in the
/// header (Ogg Vorbis/Opus).
///
/// [onBufferingCallback] a callback that is called when starting to buffer
/// and when the buffering is done.
///
/// [onMetadataCallback] a callback that is called when metadata is detected.
///
/// [onMoreDataIsNeededCallback] a callback that is called when the engine
/// needs more encoded audio data. The parameter is the byte offset in the
/// original encoded stream.
///
/// [onAudioDurationCallback] a callback that is called once the total audio
/// duration has been determined.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.UnsignedInt>,
    ffi.UnsignedInt,
    ffi.Double,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.Int,
    ffi.Uint64,
    dartOnBufferingCallback_t,
    dartOnMetadataCallback_t,
    dartOnMoreDataIsNeededCallback_t,
    dartOnAudioDurationCallback_t,
  )
>(symbol: 'setPullBufferStream')
external int _setPullBufferStream(
  ffi.Pointer<ffi.UnsignedInt> hash,
  int bufferSizeBytes,
  double bufferTriggerPosition,
  int sampleRate,
  int channels,
  int format,
  int audioSizeBytes,
  dartOnBufferingCallback_t onBufferingCallback,
  dartOnMetadataCallback_t onMetadataCallback,
  dartOnMoreDataIsNeededCallback_t onMoreDataIsNeededCallback,
  dartOnAudioDurationCallback_t onAudioDurationCallback,
);

PlayerErrors setPullBufferStream(
  ffi.Pointer<ffi.UnsignedInt> hash,
  int bufferSizeBytes,
  double bufferTriggerPosition,
  int sampleRate,
  int channels,
  int format,
  int audioSizeBytes,
  dartOnBufferingCallback_t onBufferingCallback,
  dartOnMetadataCallback_t onMetadataCallback,
  dartOnMoreDataIsNeededCallback_t onMoreDataIsNeededCallback,
  dartOnAudioDurationCallback_t onAudioDurationCallback,
) => PlayerErrors.fromValue(
  _setPullBufferStream(
    hash,
    bufferSizeBytes,
    bufferTriggerPosition,
    sampleRate,
    channels,
    format,
    audioSizeBytes,
    onBufferingCallback,
    onMetadataCallback,
    onMoreDataIsNeededCallback,
    onAudioDurationCallback,
  ),
);

/// Resets the pull buffer stream.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt)>(
  symbol: 'resetPullBufferStream',
)
external int _resetPullBufferStream(int hash);

PlayerErrors resetPullBufferStream(int hash) =>
    PlayerErrors.fromValue(_resetPullBufferStream(hash));

/// Add a chunk of audio data to the pull buffer stream.
/// [offset] the byte offset of this chunk in the original stream, or 0 for
/// the next sequential chunk.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.Pointer<ffi.UnsignedChar>,
    ffi.UnsignedInt,
    ffi.Uint64,
  )
>(symbol: 'addPullBufferDataStream')
external int _addPullBufferDataStream(
  int hash,
  ffi.Pointer<ffi.UnsignedChar> data,
  int aDataLen,
  int offset,
);

PlayerErrors addPullBufferDataStream(
  int hash,
  ffi.Pointer<ffi.UnsignedChar> data,
  int aDataLen,
  int offset,
) => PlayerErrors.fromValue(
  _addPullBufferDataStream(hash, data, aDataLen, offset),
);

/// Get the decoded time range of the pull buffer stream.
/// [startTime] returns the start time in seconds of the decoded buffer.
/// [endTime] returns the end time in seconds of the decoded buffer.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
  )
>(symbol: 'getPullBufferTimeRange')
external int _getPullBufferTimeRange(
  int hash,
  ffi.Pointer<ffi.Double> startTime,
  ffi.Pointer<ffi.Double> endTime,
);

PlayerErrors getPullBufferTimeRange(
  int hash,
  ffi.Pointer<ffi.Double> startTime,
  ffi.Pointer<ffi.Double> endTime,
) => PlayerErrors.fromValue(_getPullBufferTimeRange(hash, startTime, endTime));

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.Pointer<ffi.UnsignedChar>,
    ffi.UnsignedInt,
  )
>(symbol: 'addAudioDataStream')
external int _addAudioDataStream(
  int hash,
  ffi.Pointer<ffi.UnsignedChar> data,
  int aDataLen,
);

PlayerErrors addAudioDataStream(
  int hash,
  ffi.Pointer<ffi.UnsignedChar> data,
  int aDataLen,
) => PlayerErrors.fromValue(_addAudioDataStream(hash, data, aDataLen));

/// Set the end of the data stream.
/// [hash] the hash of the stream sound.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt)>(symbol: 'setDataIsEnded')
external int _setDataIsEnded(int hash);

PlayerErrors setDataIsEnded(int hash) =>
    PlayerErrors.fromValue(_setDataIsEnded(hash));

/// Get the current buffer size in bytes of this sound with hash [hash].
/// [hash] the hash of the stream sound.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.Pointer<ffi.UnsignedInt>)
>(symbol: 'getBufferSize')
external int _getBufferSize(int hash, ffi.Pointer<ffi.UnsignedInt> sizeInBytes);

PlayerErrors getBufferSize(
  int hash,
  ffi.Pointer<ffi.UnsignedInt> sizeInBytes,
) => PlayerErrors.fromValue(_getBufferSize(hash, sizeInBytes));

/// Load a new waveform to be played once or multiple times later
///
/// [waveform]  WAVE_SQUARE = 0,
/// WAVE_SAW,
/// WAVE_SIN,
/// WAVE_TRIANGLE,
/// WAVE_BOUNCE,
/// WAVE_JAWS,
/// WAVE_HUMPS,
/// WAVE_FSQUARE,
/// WAVE_FSAW
/// [superWave]
/// [scale]
/// [detune]
/// [hash] return hash of the sound
/// Returns [PlayerErrors.noError] if success
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Int,
    ffi.Bool,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<ffi.UnsignedInt>,
  )
>(symbol: 'loadWaveform')
external int _loadWaveform(
  int waveform,
  bool superWave,
  double scale,
  double detune,
  ffi.Pointer<ffi.UnsignedInt> hash,
);

PlayerErrors loadWaveform(
  int waveform,
  bool superWave,
  double scale,
  double detune,
  ffi.Pointer<ffi.UnsignedInt> hash,
) => PlayerErrors.fromValue(
  _loadWaveform(waveform, superWave, scale, detune, hash),
);

/// Set the scale of an already loaded waveform identified by [hash]
///
/// [hash] the unique sound hash of a waveform sound
/// [newScale]
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Float)>()
external void setWaveformScale(int hash, double newScale);

/// Set the detune of an already loaded waveform identified by [hash]
///
/// [hash] the unique sound hash of a waveform sound
/// [newDetune]
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Float)>()
external void setWaveformDetune(int hash, double newDetune);

/// Set a new frequency of an already loaded waveform identified by [hash]
///
/// [hash] the unique sound hash of a waveform sound
/// [newFreq]
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Float)>()
external void setWaveformFreq(int hash, double newFreq);

/// Set a new frequence of an already loaded waveform identified by [hash]
///
/// [hash] the unique sound hash of a waveform sound
/// [superwave]
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Bool)>()
external void setSuperWave(int hash, bool superwave);

/// Set a new wave form of an already loaded waveform identified by [hash]
///
/// [hash] the unique sound hash of a waveform sound
/// [newWaveform]   WAVE_SQUARE = 0,
/// WAVE_SAW,
/// WAVE_SIN,
/// WAVE_TRIANGLE,
/// WAVE_BOUNCE,
/// WAVE_JAWS,
/// WAVE_HUMPS,
/// WAVE_FSQUARE,
/// WAVE_FSAW
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Int)>()
external void setWaveform(int hash, int newWaveform);

/// Speech the text given
///
/// [textToSpeech]
/// Returns [PlayerErrors.noError] if success and [handle] sound identifier
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.UnsignedInt>)
>(symbol: 'speechText')
external int _speechText(
  ffi.Pointer<ffi.Char> textToSpeech,
  ffi.Pointer<ffi.UnsignedInt> handle,
);

PlayerErrors speechText(
  ffi.Pointer<ffi.Char> textToSpeech,
  ffi.Pointer<ffi.UnsignedInt> handle,
) => PlayerErrors.fromValue(_speechText(textToSpeech, handle));

/// Switch pause state for an already loaded sound identified by [handle]
///
/// [handle] the sound handle
/// Returns [PlayerErrors.noError] if success, [PlayerErrors.backendNotInited]
/// if the engine is not initialized, [PlayerErrors.soundHandleNotFound] if
/// [handle] is not valid. Unpausing posts an asynchronous device start, so
/// this never reports [PlayerErrors.audioDeviceFailedToStart].
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt)>(symbol: 'pauseSwitch')
external int _pauseSwitch(int handle);

PlayerErrors pauseSwitch(int handle) =>
    PlayerErrors.fromValue(_pauseSwitch(handle));

/// Pause or unpause already loaded sound identified by [handle]
///
/// [handle] the sound handle
/// [pause] the sound handle
/// Returns [PlayerErrors.noError] if success, [PlayerErrors.backendNotInited]
/// if the engine is not initialized, [PlayerErrors.soundHandleNotFound] if
/// [handle] is not valid. Unpausing posts an asynchronous device start, so
/// this never reports [PlayerErrors.audioDeviceFailedToStart].
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.Bool)>(
  symbol: 'setPause',
)
external int _setPause(int handle, bool pause);

PlayerErrors setPause(int handle, bool pause) =>
    PlayerErrors.fromValue(_setPause(handle, pause));

/// Gets the pause state
///
/// [handle] the sound handle
/// Return true if paused
@ffi.Native<ffi.Int Function(ffi.UnsignedInt)>()
external int getPause(int handle);

/// Set a sound's relative play speed.
/// Setting the value to 0 will cause undefined behavior, likely a crash.
/// Change the relative play speed of a sample. This changes the effective
/// sample rate while leaving the base sample rate alone.
///
/// Note that playing a sound at a higher sample rate will require SoLoud
/// to request more samples from the sound source, which will require more
/// memory and more processing power. Playing at a slower sample rate
/// is cheaper.
///
/// [handle] the sound handle
/// [speed] the new speed
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Float)>()
external void setRelativePlaySpeed(int handle, double speed);

/// Get a sound's relative play speed.
/// If an invalid handle is given to getRelativePlaySpeed, it will return 1.
///
/// [handle] the sound handle
/// Return the current play speed.
@ffi.Native<ffi.Float Function(ffi.UnsignedInt)>()
external double getRelativePlaySpeed(int handle);

/// Gets the approximate volume for output per output channel (i.e, per
/// speaker).
///
/// [channel] the channel.
/// Return zero for invalid parameters.
@ffi.Native<ffi.Float Function(ffi.UnsignedInt)>()
external double getApproximateVolume(int channel);

/// Play already loaded sound identified by [hash]
///
/// [soundHash] the unique sound hash of a sound
/// [busId] the bus ID to play the sound on. 0 means the main engine.
/// [volume] 1.0f full volume
/// [pan] 0.0f centered
/// [paused] 0 not paused
/// [looping] whether to start the sound in looping state.
/// [loopingStartAt] If looping is enabled, the loop point is, by default,
/// the start of the stream. The loop start point can be set with this
/// [loopingStartOffsetAt] Optional exact frame offset to restart looping
/// from (-1 = inactive).
/// [loopingEndOffsetAt] Optional exact frame offset to loop before
/// (-1 = inactive).
/// [scale] relative playback speed multiplier (1.0f = normal speed).
/// [handle] pointer to the handle for this new sound
/// Return the error if any and a new [handle] of this sound
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.Float,
    ffi.Float,
    ffi.Bool,
    ffi.Bool,
    ffi.Double,
    ffi.Double,
    ffi.Int,
    ffi.Int,
    ffi.Float,
    ffi.Pointer<ffi.UnsignedInt>,
  )
>(symbol: 'play')
external int _play(
  int soundHash,
  int busId,
  double volume,
  double pan,
  bool paused,
  bool looping,
  double loopingStartAt,
  double loopingEndAt,
  int loopingStartOffsetAt,
  int loopingEndOffsetAt,
  double scale,
  ffi.Pointer<ffi.UnsignedInt> handle,
);

PlayerErrors play(
  int soundHash,
  int busId,
  double volume,
  double pan,
  bool paused,
  bool looping,
  double loopingStartAt,
  double loopingEndAt,
  int loopingStartOffsetAt,
  int loopingEndOffsetAt,
  double scale,
  ffi.Pointer<ffi.UnsignedInt> handle,
) => PlayerErrors.fromValue(
  _play(
    soundHash,
    busId,
    volume,
    pan,
    paused,
    looping,
    loopingStartAt,
    loopingEndAt,
    loopingStartOffsetAt,
    loopingEndOffsetAt,
    scale,
    handle,
  ),
);

/// Variant of [play] that takes an additional parameter, the time offset
/// for the sound.
///
/// While the vanilla [play] tries to play sounds as soon as possible,
/// [playClocked] will delay the start of sounds so that rapidly launched
/// sounds don't all get clumped to the start of the next outgoing sound
/// buffer.
///
/// [soundHash] the unique sound hash of a sound
/// [soundTime] your app's "physics time", in seconds. SoLoud will use that
/// time (as well as the time previously used) to calculate the delay
/// between two sound effects.
/// [volume] 1.0f full volume
/// [pan] 0.0f centered
/// [busId] the bus ID to play the sound on. 0 means the main engine.
/// [scale] relative playback speed multiplier (1.0f = normal speed).
/// [looping] whether the sound loops upon reaching the end.
/// [loopingStartAt] time position in seconds to restart playback when
/// looping.
/// [loopingEndAt] If greater than zero, loop before this time.
/// [loopingStartOffsetAt] Optional exact frame offset to restart looping
/// from (-1 = inactive).
/// [loopingEndOffsetAt] Optional exact frame offset to loop before
/// (-1 = inactive).
/// [handle] pointer to the handle for this new sound
/// Return the error if any and a new [handle] of this sound
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.Double,
    ffi.UnsignedInt,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Bool,
    ffi.Double,
    ffi.Double,
    ffi.Int,
    ffi.Int,
    ffi.Pointer<ffi.UnsignedInt>,
  )
>(symbol: 'playClocked')
external int _playClocked(
  int soundHash,
  double soundTime,
  int busId,
  double volume,
  double pan,
  double scale,
  bool looping,
  double loopingStartAt,
  double loopingEndAt,
  int loopingStartOffsetAt,
  int loopingEndOffsetAt,
  ffi.Pointer<ffi.UnsignedInt> handle,
);

PlayerErrors playClocked(
  int soundHash,
  double soundTime,
  int busId,
  double volume,
  double pan,
  double scale,
  bool looping,
  double loopingStartAt,
  double loopingEndAt,
  int loopingStartOffsetAt,
  int loopingEndOffsetAt,
  ffi.Pointer<ffi.UnsignedInt> handle,
) => PlayerErrors.fromValue(
  _playClocked(
    soundHash,
    soundTime,
    busId,
    volume,
    pan,
    scale,
    looping,
    loopingStartAt,
    loopingEndAt,
    loopingStartOffsetAt,
    loopingEndOffsetAt,
    handle,
  ),
);

/// Set the number of samples to delay before starting to play a sound.
///
/// This is used internally by [playClocked]. In the unlikely event that
/// you may want to use it manually, it's available here. Note that calling
/// this on a "live" voice will cause silence to be inserted at the start
/// of the next audio buffer.
///
/// [handle] the sound handle
/// [samples] the number of samples to delay the sound with
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.UnsignedInt)>()
external void setDelaySamples(int handle, int samples);

/// Get the current stream time of a voice, in seconds.
///
/// [handle] the sound handle
/// Return the stream time in seconds. 0 if [handle] is invalid.
@ffi.Native<ffi.Double Function(ffi.UnsignedInt)>()
external double getStreamTime(int handle);

/// Reset the clock used by [playClocked] and [play3dClocked] to the state
/// as if they were never called.
///
/// The next clocked play will anchor the caller's "physics time" to the
/// audio clock again (leading by two output buffers).
@ffi.Native<ffi.Void Function()>()
external void resetStreamTime();

/// Get the engine's global stream time, in seconds.
///
/// This is the clock the mixer advances at the start of every output
/// buffer and the time base used by [playScheduled], [stopScheduled] and
/// [fadeScheduled]. It only advances while the audio device is mixing.
///
/// Return the engine time in seconds.
@ffi.Native<ffi.Double Function()>()
external double getEngineTime();

/// Engine time of the sample currently reaching the output device: the mix
/// clock (see [getEngineTime]) minus the render-ahead ring depth. Equals
/// [getEngineTime] when the render-ahead ring is disabled (the default).
@ffi.Native<ffi.Double Function()>()
external double getPlayheadTime();

/// Estimated output latency in seconds (render-ahead ring depth plus one
/// device period). 0 when the render-ahead ring is disabled.
@ffi.Native<ffi.Double Function()>()
external double getOutputLatency();

/// Whether the render-ahead ring (the retroactive re-mix prerequisite) is
/// active. Enabled at init time via `initEngine`'s `renderAheadFrames`.
@ffi.Native<ffi.UnsignedInt Function()>()
external int isRenderAheadEnabled();

/// Start playing a sound at an absolute engine time (see [getEngineTime]),
/// with sample accuracy.
///
/// Unlike [playClocked] there is no anchor and no re-anchor guard, so
/// sounds can be scheduled arbitrarily far in the future. A time in the
/// past plays as soon as possible.
///
/// [soundHash] the unique sound hash of a sound
/// [atTime] the absolute engine time, in seconds, at which the sound
/// should start
/// [duration] if greater than zero, the sound is automatically stopped
/// at [atTime] + [duration]
/// [busId] the bus ID to play the sound on. 0 means the main engine.
/// [volume] 1.0f full volume
/// [pan] 0.0f centered
/// [scale] relative playback speed multiplier (1.0f = normal speed)
/// [looping] whether the sound loops upon reaching the end
/// [loopingStartAt] time position in seconds to restart playback when
/// looping
/// [handle] pointer to the handle for this new sound
/// Return the error if any and a new [handle] of this sound
/// [loopingStartOffsetAt] Optional exact frame offset to restart looping
/// from (-1 = inactive).
/// [loopingEndOffsetAt] Optional exact frame offset to loop before
/// (-1 = inactive).
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.Double,
    ffi.Double,
    ffi.UnsignedInt,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Bool,
    ffi.Double,
    ffi.Double,
    ffi.Int,
    ffi.Int,
    ffi.Pointer<ffi.UnsignedInt>,
  )
>(symbol: 'playScheduled')
external int _playScheduled(
  int soundHash,
  double atTime,
  double duration,
  int busId,
  double volume,
  double pan,
  double scale,
  bool looping,
  double loopingStartAt,
  double loopingEndAt,
  int loopingStartOffsetAt,
  int loopingEndOffsetAt,
  ffi.Pointer<ffi.UnsignedInt> handle,
);

PlayerErrors playScheduled(
  int soundHash,
  double atTime,
  double duration,
  int busId,
  double volume,
  double pan,
  double scale,
  bool looping,
  double loopingStartAt,
  double loopingEndAt,
  int loopingStartOffsetAt,
  int loopingEndOffsetAt,
  ffi.Pointer<ffi.UnsignedInt> handle,
) => PlayerErrors.fromValue(
  _playScheduled(
    soundHash,
    atTime,
    duration,
    busId,
    volume,
    pan,
    scale,
    looping,
    loopingStartAt,
    loopingEndAt,
    loopingStartOffsetAt,
    loopingEndOffsetAt,
    handle,
  ),
);

/// Stop a sound at an absolute engine time (see [getEngineTime]).
///
/// A time in the past stops the sound immediately.
///
/// [handle] the sound handle
/// [atTime] the absolute engine time, in seconds, at which the sound
/// should stop
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Double)>()
external void stopScheduled(int handle, double atTime);

/// Fade the volume of a sound starting at an absolute engine time
/// (see [getEngineTime]).
///
/// The fade goes from the volume the sound has at call time to [to] over
/// [fadeTime] seconds. If [thenStop] is true, the sound is stopped when
/// the fade ends (at [atTime] + [fadeTime]).
///
/// [handle] the sound handle
/// [atTime] the absolute engine time, in seconds, at which the fade
/// should start. A time in the past starts the fade immediately.
/// [to] the ending volume of the fade
/// [fadeTime] the duration of the fade, in seconds
/// [thenStop] whether to stop the sound when the fade ends
@ffi.Native<
  ffi.Void Function(
    ffi.UnsignedInt,
    ffi.Double,
    ffi.Float,
    ffi.Double,
    ffi.Bool,
  )
>()
external void fadeScheduled(
  int handle,
  double atTime,
  double to,
  double fadeTime,
  bool thenStop,
);

/// Stop already loaded sound identified by [handle] and clear it
///
/// [handle]
/// Returns [PlayerErrors.noError] if success, [PlayerErrors.backendNotInited]
/// if the engine is not initialized, [PlayerErrors.soundHandleNotFound] if
/// [handle] is not valid (for example the voice has already ended).
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt)>(symbol: 'stop')
external int _stop(int handle);

PlayerErrors stop(int handle) => PlayerErrors.fromValue(_stop(handle));

/// Stop all playing voices without disposing the loaded sounds.
///
/// Each stopped voice triggers the voice-ended callback (dispatched by
/// SoLoud itself), so Dart is notified for every handle like with [stop].
@ffi.Native<ffi.Void Function()>()
external void stopAll();

/// Stop all voices playing the already loaded sound identified by
/// [soundHash] without disposing it.
///
/// Each stopped voice triggers the voice-ended callback (dispatched by
/// SoLoud itself), so Dart is notified for every handle like with [stop].
@ffi.Native<ffi.Void Function(ffi.UnsignedInt)>()
external void stopAudioSource(int soundHash);

/// Stop all handles of the already loaded sound identified by [hash] and
/// dispose it
///
/// [soundHash]
@ffi.Native<ffi.Void Function(ffi.UnsignedInt)>()
external void disposeSound(int soundHash);

/// Dispose all sounds already loaded
@ffi.Native<ffi.Void Function()>()
external void disposeAllSound();

/// Query whether a sound is set to loop.
///
/// [handle]
/// Returns true if flagged for looping.
@ffi.Native<ffi.Int Function(ffi.UnsignedInt)>()
external int getLooping(int handle);

/// This function can be used to set a sample to play on repeat,
/// instead of just playing once
///
/// [soundHash]
/// [enable]
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Bool)>()
external void setLooping(int handle, bool enable);

/// Get sound loop point value.
///
/// [handle]
/// Returns the time in seconds.
@ffi.Native<ffi.Double Function(ffi.UnsignedInt)>()
external double getLoopPoint(int handle);

/// Set sound loop point value.
///
/// [handle]
/// [time] in seconds.
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Double)>()
external void setLoopPoint(int handle, double time);

/// Get the sound loop end point value.
///
/// [handle]
/// Returns the time in seconds, or zero for the natural stream end.
@ffi.Native<ffi.Double Function(ffi.UnsignedInt)>()
external double getLoopEndPoint(int handle);

/// Set the sound loop end point value.
///
/// [handle]
/// [time] in seconds, or zero to use the natural stream end.
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Double)>()
external void setLoopEndPoint(int handle, double time);

/// Enable or disable visualization
///
/// [enabled] enable or disable it
/// [windowSize] power of two from 128 to 8192 (default 256)
/// [kind] 0: wave, 1: FFT, 2: wave and FFT
/// [channel] -1: merged mono, -2: all channels, >= 0: specific channel index
@ffi.Native<ffi.UnsignedInt Function(ffi.Bool, ffi.Int, ffi.Int, ffi.Int)>(
  symbol: 'setVisualizationEnabled',
)
external int _setVisualizationEnabled(
  bool enabled,
  int windowSize,
  int kind,
  int channel,
);

PlayerErrors setVisualizationEnabled(
  bool enabled,
  int windowSize,
  int kind,
  int channel,
) => PlayerErrors.fromValue(
  _setVisualizationEnabled(enabled, windowSize, kind, channel),
);

/// Get visualization state
///
/// Return true if enabled
@ffi.Native<ffi.Int Function()>()
external int getVisualizationEnabled();

/// Smooth FFT data.
/// When new data is read and the values are decreasing, the new value will
/// be decreased with an amplitude between the old and the new value.
/// This will result on a less shaky visualization.
///
/// [smooth] must be in the [0.0 ~ 1.0] range.
/// 0 = no smooth
/// 1 = full smooth
@ffi.Native<ffi.Void Function(ffi.Float)>()
external void setFftSmoothing(double smooth);

/// Get the sound length in seconds
///
/// [soundHash] the sound hash
/// Returns sound length in seconds
@ffi.Native<ffi.Double Function(ffi.UnsignedInt)>()
external double getLength(int soundHash);

/// Seek playing in [time] seconds
/// [time]
/// [handle] the sound handle
/// Returns [PlayerErrors.noError] if success
///
/// NOTE: when seeking an mp3 file loaded using `loadIntoMem`=false
/// the seek operation is not performed due to lags. This occurs because the
/// mp3 codec must compute each frame length to gain a new position.
/// The problem is explained in souloud_wavstream.cpp
/// in `WavStreamInstance::seek` function.
///
/// This mode is useful ie for background music, not for a music player
/// where a seek slider for mp3s is a must.
/// If you need seeking mp3, please, use `loadIntoMem`=true instead
/// or other audio formats!
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.Float)>(
  symbol: 'seek',
)
external int _seek(int handle, double time);

PlayerErrors seek(int handle, double time) =>
    PlayerErrors.fromValue(_seek(handle, time));

/// Get current sound position  in seconds
///
/// [handle] the sound handle
/// Returns time in seconds
@ffi.Native<ffi.Double Function(ffi.UnsignedInt)>()
external double getPosition(int handle);

/// Get current Global volume
///
/// Returns the volume
@ffi.Native<ffi.Double Function()>()
external double getGlobalVolume();

/// Set current Global volume
///
/// Returns the volume
@ffi.Native<ffi.UnsignedInt Function(ffi.Float)>(symbol: 'setGlobalVolume')
external int _setGlobalVolume(double volume);

PlayerErrors setGlobalVolume(double volume) =>
    PlayerErrors.fromValue(_setGlobalVolume(volume));

/// Get current [handle] volume
///
/// Returns the volume
@ffi.Native<ffi.Double Function(ffi.UnsignedInt)>()
external double getVolume(int handle);

/// Set current [handle] volume
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.Float)>(
  symbol: 'setVolume',
)
external int _setVolume(int handle, double volume);

PlayerErrors setVolume(int handle, double volume) =>
    PlayerErrors.fromValue(_setVolume(handle, volume));

/// Get a sound's current pan setting.
///
/// [handle] the sound handle.
/// Returns the range of the pan values is -1 to 1, where -1 is left, 0 is
/// middle and and 1 is right.
@ffi.Native<ffi.Double Function(ffi.UnsignedInt)>()
external double getPan(int handle);

/// Set a sound's current pan setting.
///
/// [handle] the sound handle.
/// [pan] the range of the pan values is -1 to 1, where -1 is left, 0 is
/// middle and and 1 is right.
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Double)>()
external void setPan(int handle, double pan);

/// Set the left/right volumes directly.
/// Note that this does not affect the value returned by getPan.
///
/// [handle] the sound handle.
/// [panLeft] value for the left pan.
/// [panRight] value for the right pan.
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Double, ffi.Double)>()
external void setPanAbsolute(int handle, double panLeft, double panRight);

/// Check if a handle is still valid.
///
/// [handle] handle to check
/// Return true if it still exists
@ffi.Native<ffi.Int Function(ffi.UnsignedInt)>()
external int getIsValidVoiceHandle(int handle);

/// Returns the number of concurrent sounds that are playing at the moment.
@ffi.Native<ffi.UnsignedInt Function()>()
external int getActiveVoiceCount();

/// Returns the number of concurrent sounds that are playing a specific audio
/// source.
@ffi.Native<ffi.Int Function(ffi.UnsignedInt)>()
external int countAudioSource(int soundHash);

/// Returns the number of voices the application has told SoLoud to play.
@ffi.Native<ffi.UnsignedInt Function()>()
external int getVoiceCount();

/// Get a sound's protection state.
@ffi.Native<ffi.Bool Function(ffi.UnsignedInt)>()
external bool getProtectVoice(int handle);

/// Set a sound's protection state.
///
/// Normally, if you try to play more sounds than there are voices,
/// SoLoud will kill off the oldest playing sound to make room.
/// This will most likely be your background music. This can be worked
/// around by protecting the sound.
/// If all voices are protected, the result will be undefined.
///
/// [handle]  handle to check.
/// [protect] whether to protect or not.
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Bool)>()
external void setProtectVoice(int handle, bool protect);

/// Set the inaudible behavior of a live sound. By default,
/// if a sound is inaudible, it's paused, and will resume when it
/// becomes audible again. With this function you can tell SoLoud
/// to either kill the sound if it becomes inaudible, or to keep
/// ticking the sound even when it's inaudible.
///
/// [handle]  handle to check.
/// [mustTick] whether to keep ticking or not when the sound becomes
/// inaudible.
/// [kill] whether to kill the sound or not when the sound becomes inaudible.
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Bool, ffi.Bool)>()
external void setInaudibleBehavior(int handle, bool mustTick, bool kill);

/// Get the current maximum active voice count.
@ffi.Native<ffi.UnsignedInt Function()>()
external int getMaxActiveVoiceCount();

/// Set the current maximum active voice count.
/// If voice count is higher than the maximum active voice count,
/// SoLoud will pick the ones with the highest volume to actually play.
/// [maxVoiceCount] the max concurrent sounds that can be played.
@ffi.Native<ffi.Void Function(ffi.UnsignedInt)>()
external void setMaxActiveVoiceCount(int maxVoiceCount);

/// Used to create a new voice group. Returns 0 if not successful.
@ffi.Native<ffi.UnsignedInt Function()>()
external int createVoiceGroup();

/// Deallocates the voice group. Does not stop the voices attached to the
/// voice group.
///
/// [handle] the group handle to destroy.
@ffi.Native<ffi.Void Function(ffi.UnsignedInt)>()
external void destroyVoiceGroup(int handle);

/// Adds voice handle to the voice group. The voice handles can still be
/// used separate from the group.
/// [voiceGroupHandle] the group handle to add the new [voiceHandle].
/// [voiceHandle] voice handle to add to the [voiceGroupHandle].
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.UnsignedInt)>()
external void addVoiceToGroup(int voiceGroupHandle, int voiceHandle);

/// Checks if the handle is a valid voice group. Does not care if the
/// voice group is empty.
///
/// [handle] the group handle to check.
/// Return true if [handle] is a group handle.
@ffi.Native<ffi.Int Function(ffi.UnsignedInt)>()
external int isVoiceGroup(int handle);

/// Checks whether a voice group is empty. SoLoud automatically trims
/// the voice groups of voices that have ended, so the group may be
/// empty even though you've added valid voice handles to it.
///
/// [handle] group handle to check.
/// Return true if the group handle doesn't have any voices.
@ffi.Native<ffi.Int Function(ffi.UnsignedInt)>()
external int isVoiceGroupEmpty(int handle);

/// Smoothly change the global volume over specified time.
@ffi.Native<ffi.UnsignedInt Function(ffi.Float, ffi.Float)>(
  symbol: 'fadeGlobalVolume',
)
external int _fadeGlobalVolume(double to, double time);

PlayerErrors fadeGlobalVolume(double to, double time) =>
    PlayerErrors.fromValue(_fadeGlobalVolume(to, time));

/// Smoothly change a channel's volume over specified time.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.Float, ffi.Float)>(
  symbol: 'fadeVolume',
)
external int _fadeVolume(int handle, double to, double time);

PlayerErrors fadeVolume(int handle, double to, double time) =>
    PlayerErrors.fromValue(_fadeVolume(handle, to, time));

/// Smoothly change a channel's pan setting over specified time.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.Float, ffi.Float)>(
  symbol: 'fadePan',
)
external int _fadePan(int handle, double to, double time);

PlayerErrors fadePan(int handle, double to, double time) =>
    PlayerErrors.fromValue(_fadePan(handle, to, time));

/// Smoothly change a channel's relative play speed over specified time.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.Float, ffi.Float)>(
  symbol: 'fadeRelativePlaySpeed',
)
external int _fadeRelativePlaySpeed(int handle, double to, double time);

PlayerErrors fadeRelativePlaySpeed(int handle, double to, double time) =>
    PlayerErrors.fromValue(_fadeRelativePlaySpeed(handle, to, time));

/// After specified time, pause the channel.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.Float)>(
  symbol: 'schedulePause',
)
external int _schedulePause(int handle, double time);

PlayerErrors schedulePause(int handle, double time) =>
    PlayerErrors.fromValue(_schedulePause(handle, time));

/// After specified time, stop the channel.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.Float)>(
  symbol: 'scheduleStop',
)
external int _scheduleStop(int handle, double time);

PlayerErrors scheduleStop(int handle, double time) =>
    PlayerErrors.fromValue(_scheduleStop(handle, time));

/// Set fader to oscillate the volume at specified frequency.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.Float, ffi.Float, ffi.Float)
>(symbol: 'oscillateVolume')
external int _oscillateVolume(int handle, double from, double to, double time);

PlayerErrors oscillateVolume(int handle, double from, double to, double time) =>
    PlayerErrors.fromValue(_oscillateVolume(handle, from, to, time));

/// Set fader to oscillate the panning at specified frequency.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.Float, ffi.Float, ffi.Float)
>(symbol: 'oscillatePan')
external int _oscillatePan(int handle, double from, double to, double time);

PlayerErrors oscillatePan(int handle, double from, double to, double time) =>
    PlayerErrors.fromValue(_oscillatePan(handle, from, to, time));

/// Set fader to oscillate the relative play speed at specified frequency.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.Float, ffi.Float, ffi.Float)
>(symbol: 'oscillateRelativePlaySpeed')
external int _oscillateRelativePlaySpeed(
  int handle,
  double from,
  double to,
  double time,
);

PlayerErrors oscillateRelativePlaySpeed(
  int handle,
  double from,
  double to,
  double time,
) =>
    PlayerErrors.fromValue(_oscillateRelativePlaySpeed(handle, from, to, time));

/// Set fader to oscillate the global volume at specified frequency.
@ffi.Native<ffi.UnsignedInt Function(ffi.Float, ffi.Float, ffi.Float)>(
  symbol: 'oscillateGlobalVolume',
)
external int _oscillateGlobalVolume(double from, double to, double time);

PlayerErrors oscillateGlobalVolume(double from, double to, double time) =>
    PlayerErrors.fromValue(_oscillateGlobalVolume(from, to, time));

/// Check if the given filter is active or not.
///
/// [soundHash] the sound to check the filter. If this is =0 this function
/// searches in the global filters.
/// [busId] the bus to check the filter.
/// If both [soundHash] and [busId] are =0 this function searches in the
/// global filters.
/// [filterType] filter to check.
/// Returns [PlayerErrors.noError] if no errors and the index of
/// the given filter (-1 if the filter is not active).
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.Pointer<ffi.Int>,
  )
>(symbol: 'isFilterActive')
external int _isFilterActive(
  int soundHash,
  int busId,
  int filterType,
  ffi.Pointer<ffi.Int> index,
);

PlayerErrors isFilterActive(
  int soundHash,
  int busId,
  FilterType filterType,
  ffi.Pointer<ffi.Int> index,
) => PlayerErrors.fromValue(
  _isFilterActive(soundHash, busId, filterType.value, index),
);

/// Get parameters names of the given filter.
///
/// [filterType] filter to get param names.
/// Returns [PlayerErrors.noError] if no errors and the list of param names.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>(symbol: 'getFilterParamNames')
external int _getFilterParamNames(
  int filterType,
  ffi.Pointer<ffi.Int> paramsCount,
  ffi.Pointer<ffi.Pointer<ffi.Char>> names,
);

PlayerErrors getFilterParamNames(
  FilterType filterType,
  ffi.Pointer<ffi.Int> paramsCount,
  ffi.Pointer<ffi.Pointer<ffi.Char>> names,
) => PlayerErrors.fromValue(
  _getFilterParamNames(filterType.value, paramsCount, names),
);

/// Add the filter [filterType] to [soundHash]. If [soundHash]==0 the
/// filter is added to global filters.
///
/// [soundHash] the sound to add the filter to.
/// [busId] the bus to check the filter.
/// If both [soundHash] and [busId] are =0 this function searches in the
/// global filters.
/// [filterType] filter to add.
/// Returns [PlayerErrors.noError] if no errors.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.UnsignedInt, ffi.UnsignedInt)
>(symbol: 'addFilter')
external int _addFilter(int soundHash, int busId, int filterType);

PlayerErrors addFilter(int soundHash, int busId, FilterType filterType) =>
    PlayerErrors.fromValue(_addFilter(soundHash, busId, filterType.value));

/// Remove the filter [filterType] from [soundHash]. If [soundHash]==0 the
/// filter is removed from the global filters.
///
/// [soundHash] the sound to add the filter to.
/// [busId] the bus to check the filter.
/// If both [soundHash] and [busId] are =0 this function searches in the
/// global filters.
/// [filterType] filter to remove.
/// Returns [PlayerErrors.noError] if no errors.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.UnsignedInt, ffi.UnsignedInt)
>(symbol: 'removeFilter')
external int _removeFilter(int soundHash, int busId, int filterType);

PlayerErrors removeFilter(int soundHash, int busId, FilterType filterType) =>
    PlayerErrors.fromValue(_removeFilter(soundHash, busId, filterType.value));

/// Set the effect parameter with id [attributeId]
/// of [filterType] with [value] value.
///
/// [handle] the handle to set the filter to. If equal to 0, the filter is
/// applyed globally.
/// [busId] the bus to set the filter to.
/// If both [handle] and [busId] are =0 this function sets the global
/// filters.
/// [filterType] filter to modify a param.
/// [attributeId] the attribute id of the filter to modify.
/// [value] the value to set the attribute to.
///
/// Returns [PlayerErrors.noError] if no errors.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.Int,
    ffi.Float,
  )
>(symbol: 'setFilterParams')
external int _setFilterParams(
  int handle,
  int busId,
  int filterType,
  int attributeId,
  double value,
);

PlayerErrors setFilterParams(
  int handle,
  int busId,
  FilterType filterType,
  int attributeId,
  double value,
) => PlayerErrors.fromValue(
  _setFilterParams(handle, busId, filterType.value, attributeId, value),
);

/// Get the effect parameter with id [attributeId] of [filterType].
///
/// [handle] the handle to get the filter to. If equal to 0, it gets the
/// global filter.
/// [busId] the bus to check the filter.
/// If both [handle] and [busId] are =0 this function searches in the global
/// filters.
/// [filterType] filter to modify a param. Returns the value of param or
/// 9999.0 if the filter is not found.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.Int,
    ffi.Pointer<ffi.Float>,
  )
>(symbol: 'getFilterParams')
external int _getFilterParams(
  int handle,
  int busId,
  int filterType,
  int attributeId,
  ffi.Pointer<ffi.Float> filterValue,
);

PlayerErrors getFilterParams(
  int handle,
  int busId,
  FilterType filterType,
  int attributeId,
  ffi.Pointer<ffi.Float> filterValue,
) => PlayerErrors.fromValue(
  _getFilterParams(handle, busId, filterType.value, attributeId, filterValue),
);

/// Fades a parameter of a filter.
///
/// [handle] the handle of the voice to apply the fade. If equal to 0, it
/// fades the global filter.
/// [busId] the bus to check the filter.
/// If both [handle] and [busId] are =0 this function searches in the global
/// filters.
/// [filterType] filter to modify a param.
/// [attributeId] the attribute index to fade.
/// [to] value the attribute should go in [time] duration.
/// [time] the fade slope duration. Returns [PlayerErrors.noError] if
/// no errors.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.Int,
    ffi.Float,
    ffi.Float,
  )
>(symbol: 'fadeFilterParameter')
external int _fadeFilterParameter(
  int handle,
  int busId,
  int filterType,
  int attributeId,
  double to,
  double time,
);

PlayerErrors fadeFilterParameter(
  int handle,
  int busId,
  FilterType filterType,
  int attributeId,
  double to,
  double time,
) => PlayerErrors.fromValue(
  _fadeFilterParameter(handle, busId, filterType.value, attributeId, to, time),
);

/// Oscillate a parameter of a filter.
///
/// [handle] the handle of the voice to apply the fade. If equal to 0, it
/// fades the global filter.
/// [busId] the bus to check the filter.
/// If both [handle] and [busId] are =0 this function searches in the global
/// filters.
/// [filterType] filter to modify a param.
/// [attributeId] the attribute index to fade.
/// [from] the starting value the attribute sould start to oscillate.
/// [to] the ending value the attribute sould end to oscillate.
/// [time] the fade slope duration.
/// Returns [PlayerErrors.noError] if no errors.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.Int,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>(symbol: 'oscillateFilterParameter')
external int _oscillateFilterParameter(
  int handle,
  int busId,
  int filterType,
  int attributeId,
  double from,
  double to,
  double time,
);

PlayerErrors oscillateFilterParameter(
  int handle,
  int busId,
  FilterType filterType,
  int attributeId,
  double from,
  double to,
  double time,
) => PlayerErrors.fromValue(
  _oscillateFilterParameter(
    handle,
    busId,
    filterType.value,
    attributeId,
    from,
    to,
    time,
  ),
);

/// play3d() is the 3d version of the play() call
///
/// [posX], [posY], [posZ] are the audio source position coordinates.
/// [velX], [velY], [velZ] are the audio source velocity.
/// [looping] whether to start the sound in looping state.
/// [loopingStartAt] If looping is enabled, the loop point is, by default,
/// the start of the stream. The loop start point can be set with this
/// parameter.
/// [handle] pointer to the handle for this new sound
/// Return the error if any
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Bool,
    ffi.Bool,
    ffi.Double,
    ffi.Pointer<ffi.UnsignedInt>,
  )
>(symbol: 'play3d')
external int _play3d(
  int soundHash,
  int busId,
  double posX,
  double posY,
  double posZ,
  double velX,
  double velY,
  double velZ,
  double volume,
  bool paused,
  bool looping,
  double loopingStartAt,
  ffi.Pointer<ffi.UnsignedInt> handle,
);

PlayerErrors play3d(
  int soundHash,
  int busId,
  double posX,
  double posY,
  double posZ,
  double velX,
  double velY,
  double velZ,
  double volume,
  bool paused,
  bool looping,
  double loopingStartAt,
  ffi.Pointer<ffi.UnsignedInt> handle,
) => PlayerErrors.fromValue(
  _play3d(
    soundHash,
    busId,
    posX,
    posY,
    posZ,
    velX,
    velY,
    velZ,
    volume,
    paused,
    looping,
    loopingStartAt,
    handle,
  ),
);

/// Play a 3D sound with an optional bounded loop region.
///
/// This additive entry point preserves the ABI of [play3d].
/// [loopingEndAt] If greater than zero, loop before this time. Zero uses
/// the natural end of the stream.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Bool,
    ffi.Bool,
    ffi.Double,
    ffi.Double,
    ffi.Int,
    ffi.Int,
    ffi.Float,
    ffi.Pointer<ffi.UnsignedInt>,
  )
>(symbol: 'play3dWithLoopPoints')
external int _play3dWithLoopPoints(
  int soundHash,
  int busId,
  double posX,
  double posY,
  double posZ,
  double velX,
  double velY,
  double velZ,
  double volume,
  bool paused,
  bool looping,
  double loopingStartAt,
  double loopingEndAt,
  int loopingStartOffsetAt,
  int loopingEndOffsetAt,
  double scale,
  ffi.Pointer<ffi.UnsignedInt> handle,
);

PlayerErrors play3dWithLoopPoints(
  int soundHash,
  int busId,
  double posX,
  double posY,
  double posZ,
  double velX,
  double velY,
  double velZ,
  double volume,
  bool paused,
  bool looping,
  double loopingStartAt,
  double loopingEndAt,
  int loopingStartOffsetAt,
  int loopingEndOffsetAt,
  double scale,
  ffi.Pointer<ffi.UnsignedInt> handle,
) => PlayerErrors.fromValue(
  _play3dWithLoopPoints(
    soundHash,
    busId,
    posX,
    posY,
    posZ,
    velX,
    velY,
    velZ,
    volume,
    paused,
    looping,
    loopingStartAt,
    loopingEndAt,
    loopingStartOffsetAt,
    loopingEndOffsetAt,
    scale,
    handle,
  ),
);

/// play3dClocked() is the 3d version of the playClocked() call.
///
/// Instead of panning like with the "2d" version of the call, the 3d
/// version requires 3d position and optionally velocity vector. Like its
/// 2d version, this one delays the start of the sound based on the
/// [soundTime] parameter, so that firing off sounds rapidly won't cause
/// the sounds to "clump" together at the start of the next sound buffer.
///
/// [soundHash] the unique sound hash of a sound
/// [soundTime] your app's "physics time", in seconds.
/// [posX], [posY], [posZ] are the audio source position coordinates.
/// [velX], [velY], [velZ] are the audio source velocity.
/// [volume] 1.0f full volume
/// [busId] the bus ID to play the sound on. 0 means the main engine.
/// [handle] pointer to the handle for this new sound
/// Return the error if any and a new [handle] of this sound
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.Double,
    ffi.UnsignedInt,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Bool,
    ffi.Double,
    ffi.Double,
    ffi.Int,
    ffi.Int,
    ffi.Pointer<ffi.UnsignedInt>,
  )
>(symbol: 'play3dClocked')
external int _play3dClocked(
  int soundHash,
  double soundTime,
  int busId,
  double posX,
  double posY,
  double posZ,
  double velX,
  double velY,
  double velZ,
  double volume,
  double scale,
  bool looping,
  double loopingStartAt,
  double loopingEndAt,
  int loopingStartOffsetAt,
  int loopingEndOffsetAt,
  ffi.Pointer<ffi.UnsignedInt> handle,
);

PlayerErrors play3dClocked(
  int soundHash,
  double soundTime,
  int busId,
  double posX,
  double posY,
  double posZ,
  double velX,
  double velY,
  double velZ,
  double volume,
  double scale,
  bool looping,
  double loopingStartAt,
  double loopingEndAt,
  int loopingStartOffsetAt,
  int loopingEndOffsetAt,
  ffi.Pointer<ffi.UnsignedInt> handle,
) => PlayerErrors.fromValue(
  _play3dClocked(
    soundHash,
    soundTime,
    busId,
    posX,
    posY,
    posZ,
    velX,
    velY,
    velZ,
    volume,
    scale,
    looping,
    loopingStartAt,
    loopingEndAt,
    loopingStartOffsetAt,
    loopingEndOffsetAt,
    handle,
  ),
);

/// play3dScheduled() is the 3d version of the playScheduled() call.
///
/// Instead of panning like with the "2d" version of the call, the 3d
/// version requires 3d position and optionally velocity vector. Like its
/// 2d version, this one starts playing a sound at an absolute engine time
/// (see [getEngineTime]), with sample accuracy.
///
/// [soundHash] the unique sound hash of a sound
/// [atTime] the absolute engine time, in seconds, at which the sound
/// should start.
/// [duration] if greater than zero, the sound is automatically stopped at
/// [atTime] + [duration].
/// [busId] the bus ID to play the sound on. 0 means the main engine.
/// [posX], [posY], [posZ] are the audio source position coordinates.
/// [velX], [velY], [velZ] are the audio source velocity.
/// [volume] 1.0f full volume
/// [scale] relative playback speed multiplier (1.0f = normal speed)
/// [looping] whether the sound loops upon reaching the end
/// [loopingStartAt] time position in seconds to restart playback when
/// looping
/// [loopingEndAt] optional exclusive end point for looping
/// [loopingStartOffsetAt] Optional exact frame offset to restart looping
/// from (-1 = inactive).
/// [loopingEndOffsetAt] Optional exact frame offset to loop before
/// (-1 = inactive).
/// [handle] pointer to the handle for this new sound
/// Return the error if any and a new [handle] of this sound
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.Double,
    ffi.Double,
    ffi.UnsignedInt,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Bool,
    ffi.Double,
    ffi.Double,
    ffi.Int,
    ffi.Int,
    ffi.Pointer<ffi.UnsignedInt>,
  )
>(symbol: 'play3dScheduled')
external int _play3dScheduled(
  int soundHash,
  double atTime,
  double duration,
  int busId,
  double posX,
  double posY,
  double posZ,
  double velX,
  double velY,
  double velZ,
  double volume,
  double scale,
  bool looping,
  double loopingStartAt,
  double loopingEndAt,
  int loopingStartOffsetAt,
  int loopingEndOffsetAt,
  ffi.Pointer<ffi.UnsignedInt> handle,
);

PlayerErrors play3dScheduled(
  int soundHash,
  double atTime,
  double duration,
  int busId,
  double posX,
  double posY,
  double posZ,
  double velX,
  double velY,
  double velZ,
  double volume,
  double scale,
  bool looping,
  double loopingStartAt,
  double loopingEndAt,
  int loopingStartOffsetAt,
  int loopingEndOffsetAt,
  ffi.Pointer<ffi.UnsignedInt> handle,
) => PlayerErrors.fromValue(
  _play3dScheduled(
    soundHash,
    atTime,
    duration,
    busId,
    posX,
    posY,
    posZ,
    velX,
    velY,
    velZ,
    volume,
    scale,
    looping,
    loopingStartAt,
    loopingEndAt,
    loopingStartOffsetAt,
    loopingEndOffsetAt,
    handle,
  ),
);

/// You can set and get the current value of the speed of
/// sound width the get3dSoundSpeed() and set3dSoundSpeed() functions.
/// The speed of sound is used to calculate doppler effects in
/// addition to the distance delay.
///
/// Since SoLoud has no knowledge of the scale of your coordinates,
/// you may need to adjust the speed of sound for these effects
/// to work correctly. The default value is 343, which assumes
/// that your world coordinates are in meters (where 1 unit is 1 meter),
/// and that the environment is dry air at around 20 degrees Celsius.
@ffi.Native<ffi.Void Function(ffi.Float)>()
external void set3dSoundSpeed(double speed);

/// Get the sound speed
@ffi.Native<ffi.Float Function()>()
external double get3dSoundSpeed();

/// You can set the position, at-vector, up-vector and velocity
/// parameters of the 3d audio listener with one call
@ffi.Native<
  ffi.Void Function(
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>()
external void set3dListenerParameters(
  double posX,
  double posY,
  double posZ,
  double atX,
  double atY,
  double atZ,
  double upX,
  double upY,
  double upZ,
  double velocityX,
  double velocityY,
  double velocityZ,
);

/// You can set the position parameter of the 3d audio listener
@ffi.Native<ffi.Void Function(ffi.Float, ffi.Float, ffi.Float)>()
external void set3dListenerPosition(double posX, double posY, double posZ);

/// You can set the "at" vector parameter of the 3d audio listener
@ffi.Native<ffi.Void Function(ffi.Float, ffi.Float, ffi.Float)>()
external void set3dListenerAt(double atX, double atY, double atZ);

/// You can set the "up" vector parameter of the 3d audio listener
@ffi.Native<ffi.Void Function(ffi.Float, ffi.Float, ffi.Float)>()
external void set3dListenerUp(double upX, double upY, double upZ);

/// You can set the listener's velocity vector parameter
@ffi.Native<ffi.Void Function(ffi.Float, ffi.Float, ffi.Float)>()
external void set3dListenerVelocity(
  double velocityX,
  double velocityY,
  double velocityZ,
);

/// You can set the position and velocity parameters of a live
/// 3d audio source with one call
@ffi.Native<
  ffi.Void Function(
    ffi.UnsignedInt,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>()
external void set3dSourceParameters(
  int handle,
  double posX,
  double posY,
  double posZ,
  double velocityX,
  double velocityY,
  double velocityZ,
);

/// You can set the position parameters of a live 3d audio source
@ffi.Native<
  ffi.Void Function(ffi.UnsignedInt, ffi.Float, ffi.Float, ffi.Float)
>()
external void set3dSourcePosition(
  int handle,
  double posX,
  double posY,
  double posZ,
);

/// You can set the velocity parameters of a live 3d audio source
@ffi.Native<
  ffi.Void Function(ffi.UnsignedInt, ffi.Float, ffi.Float, ffi.Float)
>()
external void set3dSourceVelocity(
  int handle,
  double velocityX,
  double velocityY,
  double velocityZ,
);

/// You can set the minimum and maximum distance parameters
/// of a live 3d audio source
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Float, ffi.Float)>()
external void set3dSourceMinMaxDistance(
  int handle,
  double minDistance,
  double maxDistance,
);

/// You can change the attenuation model and rolloff factor parameters
/// of a live 3d audio source.
/// The default values are NO_ATTENUATION and 1.
///
/// NO_ATTENUATION          No attenuation
/// INVERSE_DISTANCE        Inverse distance attenuation model
/// LINEAR_DISTANCE         Linear distance attenuation model
/// EXPONENTIAL_DISTANCE    Exponential distance attenuation model
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.UnsignedInt, ffi.Float)>()
external void set3dSourceAttenuation(
  int handle,
  int attenuationModel,
  double attenuationRolloffFactor,
);

/// You can change the doppler factor of a live 3d audio source
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Float)>()
external void set3dSourceDopplerFactor(int handle, double dopplerFactor);

/// //////////////////////////////////////
/// waveform audio data
/// //////////////////////////////////////
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.Char>,
    ffi.Float,
    ffi.Float,
    ffi.UnsignedLong,
    ffi.Bool,
    ffi.Pointer<ffi.Float>,
  )
>(symbol: 'readSamplesFromFile')
external int _readSamplesFromFile(
  ffi.Pointer<ffi.Char> filePath,
  double startTime,
  double endTime,
  int numSamplesNeeded,
  bool average,
  ffi.Pointer<ffi.Float> pSamples,
);

ReadSamplesErrors readSamplesFromFile(
  ffi.Pointer<ffi.Char> filePath,
  double startTime,
  double endTime,
  int numSamplesNeeded,
  bool average,
  ffi.Pointer<ffi.Float> pSamples,
) => ReadSamplesErrors.fromValue(
  _readSamplesFromFile(
    filePath,
    startTime,
    endTime,
    numSamplesNeeded,
    average,
    pSamples,
  ),
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.UnsignedChar>,
    ffi.UnsignedLong,
    ffi.Float,
    ffi.Float,
    ffi.UnsignedLong,
    ffi.Bool,
    ffi.Pointer<ffi.Float>,
  )
>(symbol: 'readSamplesFromMem')
external int _readSamplesFromMem(
  ffi.Pointer<ffi.UnsignedChar> buffer,
  int dataSize,
  double startTime,
  double endTime,
  int numSamplesNeeded,
  bool average,
  ffi.Pointer<ffi.Float> pSamples,
);

ReadSamplesErrors readSamplesFromMem(
  ffi.Pointer<ffi.UnsignedChar> buffer,
  int dataSize,
  double startTime,
  double endTime,
  int numSamplesNeeded,
  bool average,
  ffi.Pointer<ffi.Float> pSamples,
) => ReadSamplesErrors.fromValue(
  _readSamplesFromMem(
    buffer,
    dataSize,
    startTime,
    endTime,
    numSamplesNeeded,
    average,
    pSamples,
  ),
);

/// Create a new mixing bus.
/// Returns a unique bus ID (>0) to reference this bus in other calls.
@ffi.Native<ffi.UnsignedInt Function()>()
external int createBus();

/// Destroy a mixing bus by its ID.
/// Does not stop voices that were playing through the bus.
@ffi.Native<ffi.Void Function(ffi.UnsignedInt)>()
external void destroyBus(int busId);

/// Play the bus itself on the main SoLoud engine so it becomes audible.
/// You must call this before sounds routed through the bus can be heard.
///
/// [busId] the bus ID returned by createBus.
/// [volume] playback volume (1.0 = full).
/// [paused] whether to start paused.
/// [handle] set to the voice handle of the bus, or 0 on error.
/// Returns [PlayerErrors.noError] if success, [PlayerErrors.backendNotInited]
/// if the engine is not initialized, [PlayerErrors.busIdNotFound] if [busId]
/// is unknown, [PlayerErrors.failedToStartPlayback] if no voice could be
/// created for the bus. When [paused] is false the output device is started
/// asynchronously after the bus voice exists, so this never reports
/// [PlayerErrors.audioDeviceFailedToStart].
///
/// Note: to play a sound through a bus, the play() function is used with
/// the bus ID as an argument. See play() for more information.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.UnsignedInt,
    ffi.Float,
    ffi.Bool,
    ffi.Pointer<ffi.UnsignedInt>,
  )
>(symbol: 'busPlayOnEngine')
external int _busPlayOnEngine(
  int busId,
  double volume,
  bool paused,
  ffi.Pointer<ffi.UnsignedInt> handle,
);

PlayerErrors busPlayOnEngine(
  int busId,
  double volume,
  bool paused,
  ffi.Pointer<ffi.UnsignedInt> handle,
) => PlayerErrors.fromValue(_busPlayOnEngine(busId, volume, paused, handle));

/// Set the number of output channels for the bus (default is 2 = stereo).
///
/// [busId] the bus ID.
/// [channels] number of channels (1 = mono, 2 = stereo, etc.).
@ffi.Native<ffi.Int Function(ffi.UnsignedInt, ffi.UnsignedInt)>()
external int busSetChannels(int busId, int channels);

/// Enable or disable visualization data gathering for this bus.
/// Must be enabled before calling busCalcFFT, busGetWave,
/// or busGetApproximateVolume.
///
/// [busId] the bus ID.
/// [enable] true to enable, false to disable.
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.Bool)>()
external void busSetVisualizationEnable(int busId, bool enable);

/// Calculate and return 256 floats of FFT data for this bus.
/// The data ranges from low to high frequencies.
/// Visualization must be enabled first with busSetVisualizationEnable.
///
/// [busId] the bus ID.
/// Returns a pointer to 256 floats, or nullptr if the bus is not found.
@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.UnsignedInt)>()
external ffi.Pointer<ffi.Float> busCalcFFT(int busId);

/// Get 256 samples of wave data currently playing through this bus.
/// Visualization must be enabled first with busSetVisualizationEnable.
///
/// [busId] the bus ID.
/// Returns a pointer to 256 floats, or nullptr if the bus is not found.
@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.UnsignedInt)>()
external ffi.Pointer<ffi.Float> busGetWave(int busId);

/// Get the approximate output volume for a specific channel of this bus.
/// Useful for VU meters or level indicators.
/// Visualization must be enabled first.
///
/// [busId] the bus ID.
/// [channel] the output channel index (0 = left, 1 = right, etc.).
/// Returns the approximate volume, or 0 if the bus is not found.
@ffi.Native<ffi.Float Function(ffi.UnsignedInt, ffi.UnsignedInt)>()
external double busGetApproximateVolume(int busId, int channel);

/// Move a live voice (identified by its handle) into this bus.
/// The voice will be reparented so it plays through the bus.
/// Useful for dynamically routing sounds in/out of filtered busses.
///
/// [busId] the bus ID.
/// [voiceHandle] handle of the voice to annex.
@ffi.Native<ffi.Void Function(ffi.UnsignedInt, ffi.UnsignedInt)>()
external void busAnnexSound(int busId, int voiceHandle);

/// Get the number of voices currently playing through this bus.
///
/// [busId] the bus ID.
/// Returns the active voice count, or 0 if the bus is not found.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt)>()
external int busGetActiveVoiceCount(int busId);

typedef dartVoiceEndedCallback_tFunction =
    ffi.Void Function(ffi.Pointer<ffi.UnsignedInt>);
typedef DartdartVoiceEndedCallback_tFunction =
    void Function(ffi.Pointer<ffi.UnsignedInt>);

/// Callback typedefs owned by bindings.cpp (the mixer-output, visualization,
/// buffering and metadata callback typedefs come from enums.h and
/// audiobuffer/metadata_ffi.h).
typedef dartVoiceEndedCallback_t =
    ffi.Pointer<ffi.NativeFunction<dartVoiceEndedCallback_tFunction>>;

/// Possible player errors.
///
/// WARNING: Keep these in sync with `lib/src/enums.dart`.
enum PlayerErrors {
  /// No error
  noError(0),

  /// Some parameter is invalid
  invalidParameter(1),

  /// File not found
  fileNotFound(2),

  /// File found, but could not be loaded
  fileLoadFailed(3),

  /// The sound file has already been loaded
  fileAlreadyLoaded(4),

  /// DLL not found, or wrong DLL
  dllNotFound(5),

  /// Out of memory
  outOfMemory(6),

  /// Feature not implemented
  notImplemented(7),

  /// Other error
  unknownError(8),

  /// Player not initialized
  nullPointer(9),

  /// Audio sound hash is not found
  soundHashNotFound(10),

  /// Player not initialized
  backendNotInited(11),

  /// Filter not found
  filterNotFound(12),

  /// Asking for wave and FFT is not enabled
  visualizationNotEnabled(13),

  /// The maximum number of filters has been reached (default is 8).
  maxNumberOfFiltersReached(14),

  /// The filter has already been added.
  filterAlreadyAdded(15),

  /// Player already inited.
  playerAlreadyInited(16),

  /// Audio handle is not found.
  soundHandleNotFound(17),

  /// Error getting filter parameter.
  filterParameterGetError(18),

  /// No playback devices were found.
  noPlaybackDevicesFound(19),

  /// Trying to add PCM data but the buffer is full or not large
  /// enough for the needed PCM data. Try increasing the buffer size.
  pcmBufferFull(20),

  /// Given hash doesn't belong to a buffer stream.
  hashIsNotABufferStream(21),

  /// Trying to add PCM data but the stream is marked to be ended
  /// already, by the user or when the stream reached its maximum
  /// capacity, in this case the stream is automatically marked to be ended.
  streamEndedAlready(22),

  /// Failed to create Opus decoder.
  failedToCreateOpusDecoder(23),

  /// Failed to decode Opus packet.
  failedToDecodeOpusPacket(24),

  /// A BufferStream using `release` buffer type can be played only once.
  bufferStreamCanBePlayedOnlyOnce(25),

  /// The maximum number of active voices has been reached.
  maxActiveVoiceCountReached(26),

  /// Trying to get time consumed from wrong buffer type.
  wrongBufferTypeToAskForTimeConsumed(27),

  /// Buffer stream with released buffer type, cannot be seeked.
  bufferStreamWithReleasedBufferTypeCannotBeSeeked(28),

  /// Audio format not supported.
  audioFormatNotSupported(29),

  /// Xiph libraries not found.
  xiphLibsNotFound(30),

  /// Bus ID not found.
  busIdNotFound(31),

  /// Given hash doesn't belong to a pull buffer stream.
  hashIsNotAPullBufferStream(32),

  /// The pull buffer stream is in an invalid state for this operation.
  invalidPullBufferState(33),

  /// The output audio device could not be started or resumed.
  audioDeviceFailedToStart(34),

  /// SoLoud didn't return a valid voice handle when starting the playback.
  failedToStartPlayback(35);

  final int value;
  const PlayerErrors(this.value);

  static PlayerErrors fromValue(int value) => switch (value) {
    0 => noError,
    1 => invalidParameter,
    2 => fileNotFound,
    3 => fileLoadFailed,
    4 => fileAlreadyLoaded,
    5 => dllNotFound,
    6 => outOfMemory,
    7 => notImplemented,
    8 => unknownError,
    9 => nullPointer,
    10 => soundHashNotFound,
    11 => backendNotInited,
    12 => filterNotFound,
    13 => visualizationNotEnabled,
    14 => maxNumberOfFiltersReached,
    15 => filterAlreadyAdded,
    16 => playerAlreadyInited,
    17 => soundHandleNotFound,
    18 => filterParameterGetError,
    19 => noPlaybackDevicesFound,
    20 => pcmBufferFull,
    21 => hashIsNotABufferStream,
    22 => streamEndedAlready,
    23 => failedToCreateOpusDecoder,
    24 => failedToDecodeOpusPacket,
    25 => bufferStreamCanBePlayedOnlyOnce,
    26 => maxActiveVoiceCountReached,
    27 => wrongBufferTypeToAskForTimeConsumed,
    28 => bufferStreamWithReleasedBufferTypeCannotBeSeeked,
    29 => audioFormatNotSupported,
    30 => xiphLibsNotFound,
    31 => busIdNotFound,
    32 => hashIsNotAPullBufferStream,
    33 => invalidPullBufferState,
    34 => audioDeviceFailedToStart,
    35 => failedToStartPlayback,
    _ => throw ArgumentError('Unknown value for PlayerErrors: $value'),
  };
}

typedef dartFileLoadedCallback_tFunction =
    ffi.Void Function(
      ffi.Pointer<ffi.UnsignedInt>,
      ffi.Pointer<ffi.Char>,
      ffi.Pointer<ffi.UnsignedInt>,
      ffi.Pointer<ffi.Uint64>,
    );
typedef DartdartFileLoadedCallback_tFunction =
    void Function(
      ffi.Pointer<ffi.UnsignedInt>,
      ffi.Pointer<ffi.Char>,
      ffi.Pointer<ffi.UnsignedInt>,
      ffi.Pointer<ffi.Uint64>,
    );
typedef dartFileLoadedCallback_t =
    ffi.Pointer<ffi.NativeFunction<dartFileLoadedCallback_tFunction>>;

enum PlayerStateEvents {
  event_started(0),
  event_stopped(1),
  event_rerouted(2),
  event_interruption_began(3),
  event_interruption_ended(4),
  event_unlocked(5),

  /// An automatic output-device start failed, after the backend had already
  /// rebuilt the device and retried. Emitted by the lifecycle scheduler, not by
  /// the OS, so unlike the notifications above it is reliable on every backend.
  ///
  /// WARNING: Keep in sync with `PlayerStateNotification` in
  /// `lib/src/enums.dart`; the Dart side indexes this by ordinal.
  event_audio_device_start_failed(6);

  final int value;
  const PlayerStateEvents(this.value);

  static PlayerStateEvents fromValue(int value) => switch (value) {
    0 => event_started,
    1 => event_stopped,
    2 => event_rerouted,
    3 => event_interruption_began,
    4 => event_interruption_ended,
    5 => event_unlocked,
    6 => event_audio_device_start_failed,
    _ => throw ArgumentError('Unknown value for PlayerStateEvents: $value'),
  };
}

typedef dartStateChangedCallback_tFunction =
    ffi.Void Function(ffi.Pointer<ffi.UnsignedInt>);
typedef DartdartStateChangedCallback_tFunction =
    void Function(ffi.Pointer<ffi.UnsignedInt>);
typedef dartStateChangedCallback_t =
    ffi.Pointer<ffi.NativeFunction<dartStateChangedCallback_tFunction>>;
typedef dartMixerOutputDataCallback_tFunction =
    ffi.Void Function(ffi.Pointer<ffi.UnsignedChar> data, ffi.Uint64 length);
typedef DartdartMixerOutputDataCallback_tFunction =
    void Function(ffi.Pointer<ffi.UnsignedChar> data, int length);

/// callback handing dart a chunk of captured mixer output. Declared here rather
/// than in bindings.cpp so `bindings.h` -- the ffigen entry point -- can name
/// it in the exports that take one.
typedef dartMixerOutputDataCallback_t =
    ffi.Pointer<ffi.NativeFunction<dartMixerOutputDataCallback_tFunction>>;
typedef dartVisualizationCallback_tFunction =
    ffi.Void Function(
      ffi.Int32 channelCount,
      ffi.Pointer<ffi.Pointer<ffi.Float>> waveDataPerChannel,
      ffi.Int32 waveSamples,
      ffi.Pointer<ffi.Pointer<ffi.Float>> fftDataPerChannel,
      ffi.Int32 fftSamples,
    );
typedef DartdartVisualizationCallback_tFunction =
    void Function(
      int channelCount,
      ffi.Pointer<ffi.Pointer<ffi.Float>> waveDataPerChannel,
      int waveSamples,
      ffi.Pointer<ffi.Pointer<ffi.Float>> fftDataPerChannel,
      int fftSamples,
    );

/// Callback handing dart visualization data (wave and/or FFT) per channel.
typedef dartVisualizationCallback_t =
    ffi.Pointer<ffi.NativeFunction<dartVisualizationCallback_tFunction>>;

/// The state of the audio output device.
///
/// The values mirror miniaudio's `ma_device_state` so they can be returned
/// directly from the backend without translation.
///
/// WARNING: Keep these in sync with `lib/src/enums.dart`.
/// WARNING: Keep these in sync with `lib/src/enums.dart`.
enum AudioDeviceState {
  /// The device is uninitialized. Also returned before the engine is
  /// initialized or after it has been deinitialized.
  audioDeviceUninitialized(0),

  /// The device is stopped. This is the device's default state right after
  /// initialization.
  audioDeviceStopped(1),

  /// The device is started and is requesting and/or delivering audio data.
  audioDeviceStarted(2),

  /// The device is transitioning from a stopped state to a started state.
  audioDeviceStarting(3),

  /// The device is transitioning from a started state to a stopped state.
  audioDeviceStopping(4);

  final int value;
  const AudioDeviceState(this.value);

  static AudioDeviceState fromValue(int value) => switch (value) {
    0 => audioDeviceUninitialized,
    1 => audioDeviceStopped,
    2 => audioDeviceStarted,
    3 => audioDeviceStarting,
    4 => audioDeviceStopping,
    _ => throw ArgumentError('Unknown value for AudioDeviceState: $value'),
  };
}

typedef dartOnBufferingCallback_tFunction =
    ffi.Void Function(
      ffi.Bool isBuffering,
      ffi.UnsignedInt handle,
      ffi.Double time,
    );
typedef DartdartOnBufferingCallback_tFunction =
    void Function(bool isBuffering, int handle, double time);

/// callback to tell dart that we are buffering/unbuffering
typedef dartOnBufferingCallback_t =
    ffi.Pointer<ffi.NativeFunction<dartOnBufferingCallback_tFunction>>;

/// Strucs to send metadata from C to Dart.
/// The "AudioMetadata" strucs got from *_stream_decoder.cpp in the getMetadata(),
/// will be converted to these to be sent to Dart.
enum DetectedTypeFFI {
  UNKNOWN(0),
  OGG_OPUS(1),
  OGG_VORBIS(2),
  OGG_FLAC(3),
  MP3_WITH_ID3(4),
  MP3_STREAM(5),
  WAV(6);

  final int value;
  const DetectedTypeFFI(this.value);

  static DetectedTypeFFI fromValue(int value) => switch (value) {
    0 => UNKNOWN,
    1 => OGG_OPUS,
    2 => OGG_VORBIS,
    3 => OGG_FLAC,
    4 => MP3_WITH_ID3,
    5 => MP3_STREAM,
    6 => WAV,
    _ => throw ArgumentError('Unknown value for DetectedTypeFFI: $value'),
  };
}

final class Mp3MetadataFFI extends ffi.Struct {
  @ffi.Array.multi([1024])
  external ffi.Array<ffi.Char> title;

  @ffi.Array.multi([1024])
  external ffi.Array<ffi.Char> artist;

  @ffi.Array.multi([1024])
  external ffi.Array<ffi.Char> album;

  @ffi.Array.multi([1024])
  external ffi.Array<ffi.Char> date;

  @ffi.Array.multi([1024])
  external ffi.Array<ffi.Char> genre;
}

/// Comment key-value pair structure
final class CommentPairFFI extends ffi.Struct {
  @ffi.Array.multi([1024])
  external ffi.Array<ffi.Char> key;

  @ffi.Array.multi([1024])
  external ffi.Array<ffi.Char> value;
}

/// Structure to hold track metadata
final class VorbisInfoFFI extends ffi.Struct {
  /// Dont' use here the vorbis_info struct because the lib could be not linked
  @ffi.Int()
  external int version;

  @ffi.Int()
  external int channels;

  @ffi.Long()
  external int rate;

  /// The below bitrate declarations are *hints*.
  /// Combinations of the three values carry the following implications:
  ///
  /// all three set to the same value:
  /// implies a fixed rate bitstream
  /// only nominal set:
  /// implies a VBR stream that averages the nominal bitrate.  No hard
  /// upper/lower limit
  /// upper and or lower set:
  /// implies a VBR bitstream that obeys the bitrate limits. nominal
  /// may also be set to give a nominal rate.
  /// none set:
  /// the coder does not care to speculate.
  @ffi.Long()
  external int bitrate_upper;

  @ffi.Long()
  external int bitrate_nominal;

  @ffi.Long()
  external int bitrate_lower;

  @ffi.Long()
  external int bitrate_window;
}

final class OpusInfoFFI extends ffi.Struct {
  @ffi.Uint8()
  external int version;

  @ffi.Uint8()
  external int channels;

  @ffi.Uint16()
  external int pre_skip;

  @ffi.Uint32()
  external int input_sample_rate;

  /// signed, Q8 dB
  @ffi.Int16()
  external int output_gain;

  @ffi.Uint8()
  external int mapping_family;

  /// Optional fields if mapping_family != 0
  @ffi.Uint8()
  external int stream_count;

  @ffi.Uint8()
  external int coupled_count;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> channel_mapping;

  @ffi.Int()
  external int channel_mapping_size;
}

final class FlacInfoFFI extends ffi.Struct {
  @ffi.Uint32()
  external int min_blocksize;

  @ffi.Uint32()
  external int max_blocksize;

  @ffi.Uint32()
  external int min_framesize;

  @ffi.Uint32()
  external int max_framesize;

  @ffi.Uint32()
  external int sample_rate;

  @ffi.Uint32()
  external int channels;

  @ffi.Uint32()
  external int bits_per_sample;

  @ffi.Uint32()
  external int total_samples;
}

final class OggMetadataFFI extends ffi.Struct {
  @ffi.Array.multi([1024])
  external ffi.Array<ffi.Char> vendor;

  @ffi.Uint32()
  external int commentsCount;

  @ffi.Array.multi([32])
  external ffi.Array<CommentPairFFI> comments;

  external VorbisInfoFFI vorbisInfo;

  external OpusInfoFFI opusInfo;

  external FlacInfoFFI flacInfo;
}

final class AudioMetadataFFI extends ffi.Struct {
  @ffi.UnsignedInt()
  external int detectedTypeAsInt;

  DetectedTypeFFI get detectedType =>
      DetectedTypeFFI.fromValue(detectedTypeAsInt);

  external Mp3MetadataFFI mp3Metadata;

  external OggMetadataFFI oggMetadata;
}

typedef dartOnMetadataCallback_tFunction =
    ffi.Void Function(AudioMetadataFFI metadata);
typedef DartdartOnMetadataCallback_tFunction =
    void Function(AudioMetadataFFI metadata);

/// callback to tell dart the metadata
typedef dartOnMetadataCallback_t =
    ffi.Pointer<ffi.NativeFunction<dartOnMetadataCallback_tFunction>>;
typedef dartOnMoreDataIsNeededCallback_tFunction =
    ffi.Void Function(ffi.Uint64 offset);
typedef DartdartOnMoreDataIsNeededCallback_tFunction =
    void Function(int offset);

/// callback to tell dart that more encoded data is needed
typedef dartOnMoreDataIsNeededCallback_t =
    ffi.Pointer<ffi.NativeFunction<dartOnMoreDataIsNeededCallback_tFunction>>;
typedef dartOnAudioDurationCallback_tFunction =
    ffi.Void Function(ffi.Double duration);
typedef DartdartOnAudioDurationCallback_tFunction =
    void Function(double duration);

/// callback to tell dart the total audio duration of a pull-buffer stream
typedef dartOnAudioDurationCallback_t =
    ffi.Pointer<ffi.NativeFunction<dartOnAudioDurationCallback_tFunction>>;

enum FilterType {
  BiquadResonantFilter(0),
  EchoFilter(1),
  LofiFilter(2),
  FlangerFilter(3),
  BassboostFilter(4),
  WaveShaperFilter(5),
  RobotizeFilter(6),
  FreeverbFilter(7),
  PitchShiftFilter(8),
  LimiterFilter(9),
  CompressorFilter(10),
  ParametricEQFilter(11);

  final int value;
  const FilterType(this.value);

  static FilterType fromValue(int value) => switch (value) {
    0 => BiquadResonantFilter,
    1 => EchoFilter,
    2 => LofiFilter,
    3 => FlangerFilter,
    4 => BassboostFilter,
    5 => WaveShaperFilter,
    6 => RobotizeFilter,
    7 => FreeverbFilter,
    8 => PitchShiftFilter,
    9 => LimiterFilter,
    10 => CompressorFilter,
    11 => ParametricEQFilter,
    _ => throw ArgumentError('Unknown value for FilterType: $value'),
  };
}

/// Possible read sample errors
enum ReadSamplesErrors {
  /// No error
  readSamplesNoError(0),

  /// Initialization failed. Probably an unsupported format.
  noBackend(1),

  /// Failed to retrieve decoder data format.
  failedToGetDataFormat(2),

  /// Failed to seek audio data.
  failedToSeekPcm(3),

  /// Failed to read PCM frames.
  failedToReadPcmFrames(4);

  final int value;
  const ReadSamplesErrors(this.value);

  static ReadSamplesErrors fromValue(int value) => switch (value) {
    0 => readSamplesNoError,
    1 => noBackend,
    2 => failedToGetDataFormat,
    3 => failedToSeekPcm,
    4 => failedToReadPcmFrames,
    _ => throw ArgumentError('Unknown value for ReadSamplesErrors: $value'),
  };
}
