# Configuration file for nginx. Used to serve this folder audios and to be used
# in the example/lib/pull_buffer/http_range_stream.dart

events {}

http {
    server {
        listen 8088;
        server_name localhost;

        root /Volumes/NVME/workspace/libs/flutter_soloud/example/assets/audio;
        autoindex on;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}

# nginx -c "$(pwd)/nginx.conf" -p "$(pwd)"

# nginx -s stop -c "$(pwd)/nginx.conf" -p "$(pwd)"`