#!/bin/bash

#
# Switching from SPM to CocoaPods script.
# It remove the generated Runner.xcodeproj and re-run flutter create . --platforms=macos,ios
#
# Runner.xcodeproj is generated by flutter create and is not recreated during flutter build or flutter clean.
# By deleting it and re-running flutter create . --platforms=macos, Flutter recreates a clean project from the macOS template.
# Existing source files in macos/Runner/ (like AppDelegate.swift, MainMenu.xib, Info.plist) are preserved because flutter create does not overwrite existing files.
# CocoaPods integration is restored by running pod install in the regenerated project.

cd ../example
rm -rf macos/Runner.xcodeproj macos/Runner.xcworkspace
rm -rf ios/Runner.xcodeproj ios/Runner.xcworkspace
flutter create . --platforms=macos
flutter create . --platforms=ios
cd macos
pod install
cd -
cd ios
pod install
cd -
cd -